<?php
/**
 * Created by PhpStorm.
 * User: lsw
 * Date: 18-5-15
 * Time: 下午4:01
 */

namespace Ddb\Controllers;


use Ddb\Core\ViewBaseController;

class AdminAuthController extends ViewBaseController
{
    protected $currentUser = false;

    public function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
        if (!$this->session->has("user_auth_identity")) {
            return $this->response->redirect('/admin/login');
        } else {
            $this->currentUser = service("user/query")->getCurrentUser();
            //添加左侧边栏的统计信息
            $overviewData = service("user/query")->getAdminStatistic();
            $this->view->setVar('overviewData', $overviewData);
        }
    }
}