<?php
/**
 * Created by PhpStorm.
 * User: lsw
 * Date: 18-5-15
 * Time: 下午4:01
 */

namespace Ddb\Controllers;


use Ddb\Core\ViewBaseController;

class AdminAuthController extends ViewBaseController
{
    protected $currentUser = false;

    public function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
        if (!$this->session->has("user_auth_identity")) {
            $this->response->redirect('/admin/login');
            return false;
        } else {
            $this->currentUser = service("user/query")->getCurrentUser();
        }
    }
}