<?php
/**
 * Created by PhpStorm.
 * User: lsw
 * Date: 18-5-15
 * Time: 下午4:01
 */

namespace Ddb\Controllers;


use Ddb\Core\ViewBaseController;

class AdminAuthController extends ViewBaseController
{
    public function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
        $token = $this->request->getHeader("token");
        if ($token == "") {
            return $this->response->redirect("/admin/index/login");
        } else {
            $this->token = $token;
            //用户更新信息时,需求重新写入缓存
            $this->currentMember = unserialize(di("cache")->get($token));
        }
    }

}