<?php

namespace Ddb\Models;

/**
 * Accesses
 * 
 * @package Ddb\Models
 * @autogenerated by Phalcon Developer Utils
 * @date 2018-04-25, 13:10:51
 * 
 * @method static static findFirstByParentId($parent_id)
 * @method static static[] findByParentId($parent_id)
 * @method static int countByParentId($parent_id)
 * @method static static findFirstByAccessId($access_id)
 * @method static static[] findByAccessId($access_id)
 * @method static int countByAccessId($access_id)
 * @method static static findFirstByModelId($model_id)
 * @method static static[] findByModelId($model_id)
 * @method static int countByModelId($model_id)
 */
class Accesses extends BaseModel
{

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var integer
     */
    protected $parent_id;

    /**
     *
     * @var integer
     */
    protected $access_id;

    /**
     *
     * @var integer
     */
    protected $model_id;

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return static
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field parent_id
     *
     * @param integer $parent_id
     * @return static
     */
    public function setParentId($parent_id)
    {
        $this->parent_id = $parent_id;

        return $this;
    }

    /**
     * Method to set the value of field access_id
     *
     * @param integer $access_id
     * @return static
     */
    public function setAccessId($access_id)
    {
        $this->access_id = $access_id;

        return $this;
    }

    /**
     * Method to set the value of field model_id
     *
     * @param integer $model_id
     * @return static
     */
    public function setModelId($model_id)
    {
        $this->model_id = $model_id;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field parent_id
     *
     * @return integer
     */
    public function getParentId()
    {
        return $this->parent_id;
    }

    /**
     * Returns the value of field access_id
     *
     * @return integer
     */
    public function getAccessId()
    {
        return $this->access_id;
    }

    /**
     * Returns the value of field model_id
     *
     * @return integer
     */
    public function getModelId()
    {
        return $this->model_id;
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'accesses';
    }

}
