<?php

namespace Ddb\Models;

/**
 * AppealCallbacks
 * 
 * @package Ddb\Models
 * @autogenerated by Phalcon Developer Utils
 * @date 2018-04-25, 13:10:51
 * 
 * @method static static findFirstByAppealId($appeal_id)
 * @method static static[] findByAppealId($appeal_id)
 * @method static int countByAppealId($appeal_id)
 * @method static static findFirstByWaitTime($wait_time)
 * @method static static[] findByWaitTime($wait_time)
 * @method static int countByWaitTime($wait_time)
 * @method static static findFirstByFixTime($fix_time)
 * @method static static[] findByFixTime($fix_time)
 * @method static int countByFixTime($fix_time)
 * @method static static findFirstByPrice($price)
 * @method static static[] findByPrice($price)
 * @method static int countByPrice($price)
 * @method static static findFirstByScore($score)
 * @method static static[] findByScore($score)
 * @method static int countByScore($score)
 * @method static static findFirstByContent($content)
 * @method static static[] findByContent($content)
 * @method static int countByContent($content)
 * @method static static findFirstByCreatedAt($created_at)
 * @method static static[] findByCreatedAt($created_at)
 * @method static int countByCreatedAt($created_at)
 * @method static static findFirstByUpdatedAt($updated_at)
 * @method static static[] findByUpdatedAt($updated_at)
 * @method static int countByUpdatedAt($updated_at)
 */
class AppealCallbacks extends BaseModel
{

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var integer
     */
    protected $appeal_id;

    /**
     *
     * @var integer
     */
    protected $wait_time;

    /**
     *
     * @var integer
     */
    protected $fix_time;

    /**
     *
     * @var double
     */
    protected $price;

    /**
     *
     * @var integer
     */
    protected $score;

    /**
     *
     * @var string
     */
    protected $content;

    /**
     *
     * @var string
     */
    protected $created_at;

    /**
     *
     * @var string
     */
    protected $updated_at;

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return static
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field appeal_id
     *
     * @param integer $appeal_id
     * @return static
     */
    public function setAppealId($appeal_id)
    {
        $this->appeal_id = $appeal_id;

        return $this;
    }

    /**
     * Method to set the value of field wait_time
     *
     * @param integer $wait_time
     * @return static
     */
    public function setWaitTime($wait_time)
    {
        $this->wait_time = $wait_time;

        return $this;
    }

    /**
     * Method to set the value of field fix_time
     *
     * @param integer $fix_time
     * @return static
     */
    public function setFixTime($fix_time)
    {
        $this->fix_time = $fix_time;

        return $this;
    }

    /**
     * Method to set the value of field price
     *
     * @param double $price
     * @return static
     */
    public function setPrice($price)
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Method to set the value of field score
     *
     * @param integer $score
     * @return static
     */
    public function setScore($score)
    {
        $this->score = $score;

        return $this;
    }

    /**
     * Method to set the value of field content
     *
     * @param string $content
     * @return static
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Method to set the value of field created_at
     *
     * @param string $created_at
     * @return static
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Method to set the value of field updated_at
     *
     * @param string $updated_at
     * @return static
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field appeal_id
     *
     * @return integer
     */
    public function getAppealId()
    {
        return $this->appeal_id;
    }

    /**
     * Returns the value of field wait_time
     *
     * @return integer
     */
    public function getWaitTime()
    {
        return $this->wait_time;
    }

    /**
     * Returns the value of field fix_time
     *
     * @return integer
     */
    public function getFixTime()
    {
        return $this->fix_time;
    }

    /**
     * Returns the value of field price
     *
     * @return double
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Returns the value of field score
     *
     * @return integer
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * Returns the value of field content
     *
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Returns the value of field created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Returns the value of field updated_at
     *
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'appeal_callbacks';
    }

}
