<?php

namespace Ddb\Models;

/**
 * Appeals
 * 
 * @package Ddb\Models
 * @autogenerated by Phalcon Developer Utils
 * @date 2018-06-07, 09:59:20
 * 
 * @method static static findFirstByAskId($ask_id)
 * @method static static[] findByAskId($ask_id)
 * @method static int countByAskId($ask_id)
 * @method static static findFirstByAwrId($awr_id)
 * @method static static[] findByAwrId($awr_id)
 * @method static int countByAwrId($awr_id)
 * @method static static findFirstByMethod($method)
 * @method static static[] findByMethod($method)
 * @method static int countByMethod($method)
 * @method static static findFirstByType($type)
 * @method static static[] findByType($type)
 * @method static int countByType($type)
 * @method static static findFirstByDescription($description)
 * @method static static[] findByDescription($description)
 * @method static int countByDescription($description)
 * @method static static findFirstByMobile($mobile)
 * @method static static[] findByMobile($mobile)
 * @method static int countByMobile($mobile)
 * @method static static findFirstByLongitude($longitude)
 * @method static static[] findByLongitude($longitude)
 * @method static int countByLongitude($longitude)
 * @method static static findFirstByLatitude($latitude)
 * @method static static[] findByLatitude($latitude)
 * @method static int countByLatitude($latitude)
 * @method static static findFirstByPoints($points)
 * @method static static[] findByPoints($points)
 * @method static int countByPoints($points)
 * @method static static findFirstByUpdates($updates)
 * @method static static[] findByUpdates($updates)
 * @method static int countByUpdates($updates)
 * @method static static findFirstByUpdateDesc($update_desc)
 * @method static static[] findByUpdateDesc($update_desc)
 * @method static int countByUpdateDesc($update_desc)
 * @method static static findFirstByAwrTime($awr_time)
 * @method static static[] findByAwrTime($awr_time)
 * @method static int countByAwrTime($awr_time)
 * @method static static findFirstByAwrCancelTime($awr_cancel_time)
 * @method static static[] findByAwrCancelTime($awr_cancel_time)
 * @method static int countByAwrCancelTime($awr_cancel_time)
 * @method static static findFirstByAwrFinTime($awr_fin_time)
 * @method static static[] findByAwrFinTime($awr_fin_time)
 * @method static int countByAwrFinTime($awr_fin_time)
 * @method static static findFirstByCreatedAt($created_at)
 * @method static static[] findByCreatedAt($created_at)
 * @method static int countByCreatedAt($created_at)
 * @method static static findFirstByUpdatedAt($updated_at)
 * @method static static[] findByUpdatedAt($updated_at)
 * @method static int countByUpdatedAt($updated_at)
 */
class Appeals extends BaseModel
{

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var integer
     */
    protected $ask_id;

    /**
     *
     * @var integer
     */
    protected $awr_id;

    /**
     *
     * @var integer
     */
    protected $method;

    /**
     *
     * @var integer
     */
    protected $type;

    /**
     *
     * @var string
     */
    protected $description;

    /**
     *
     * @var string
     */
    protected $mobile;

    /**
     *
     * @var string
     */
    protected $longitude;

    /**
     *
     * @var string
     */
    protected $latitude;

    /**
     *
     * @var integer
     */
    protected $points;

    /**
     *
     * @var integer
     */
    protected $updates;

    /**
     *
     * @var string
     */
    protected $update_desc;

    /**
     *
     * @var integer
     */
    protected $status;

    /**
     *
     * @var string
     */
    protected $awr_time;

    /**
     *
     * @var string
     */
    protected $awr_cancel_time;

    /**
     *
     * @var string
     */
    protected $awr_fin_time;

    /**
     *
     * @var string
     */
    protected $created_at;

    /**
     *
     * @var string
     */
    protected $updated_at;

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return static
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field ask_id
     *
     * @param integer $ask_id
     * @return static
     */
    public function setAskId($ask_id)
    {
        $this->ask_id = $ask_id;

        return $this;
    }

    /**
     * Method to set the value of field awr_id
     *
     * @param integer $awr_id
     * @return static
     */
    public function setAwrId($awr_id)
    {
        $this->awr_id = $awr_id;

        return $this;
    }

    /**
     * Method to set the value of field method
     *
     * @param integer $method
     * @return static
     */
    public function setMethod($method)
    {
        $this->method = $method;

        return $this;
    }

    /**
     * Method to set the value of field type
     *
     * @param integer $type
     * @return static
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Method to set the value of field description
     *
     * @param string $description
     * @return static
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Method to set the value of field mobile
     *
     * @param string $mobile
     * @return static
     */
    public function setMobile($mobile)
    {
        $this->mobile = $mobile;

        return $this;
    }

    /**
     * Method to set the value of field longitude
     *
     * @param string $longitude
     * @return static
     */
    public function setLongitude($longitude)
    {
        $this->longitude = $longitude;

        return $this;
    }

    /**
     * Method to set the value of field latitude
     *
     * @param string $latitude
     * @return static
     */
    public function setLatitude($latitude)
    {
        $this->latitude = $latitude;

        return $this;
    }

    /**
     * Method to set the value of field points
     *
     * @param integer $points
     * @return static
     */
    public function setPoints($points)
    {
        $this->points = $points;

        return $this;
    }

    /**
     * Method to set the value of field updates
     *
     * @param integer $updates
     * @return static
     */
    public function setUpdates($updates)
    {
        $this->updates = $updates;

        return $this;
    }

    /**
     * Method to set the value of field update_desc
     *
     * @param string $update_desc
     * @return static
     */
    public function setUpdateDesc($update_desc)
    {
        $this->update_desc = $update_desc;

        return $this;
    }

    /**
     * Method to set the value of field status
     *
     * @param integer $status
     * @return static
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Method to set the value of field awr_time
     *
     * @param string $awr_time
     * @return static
     */
    public function setAwrTime($awr_time)
    {
        $this->awr_time = $awr_time;

        return $this;
    }

    /**
     * Method to set the value of field awr_cancel_time
     *
     * @param string $awr_cancel_time
     * @return static
     */
    public function setAwrCancelTime($awr_cancel_time)
    {
        $this->awr_cancel_time = $awr_cancel_time;

        return $this;
    }

    /**
     * Method to set the value of field awr_fin_time
     *
     * @param string $awr_fin_time
     * @return static
     */
    public function setAwrFinTime($awr_fin_time)
    {
        $this->awr_fin_time = $awr_fin_time;

        return $this;
    }

    /**
     * Method to set the value of field created_at
     *
     * @param string $created_at
     * @return static
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Method to set the value of field updated_at
     *
     * @param string $updated_at
     * @return static
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field ask_id
     *
     * @return integer
     */
    public function getAskId()
    {
        return $this->ask_id;
    }

    /**
     * Returns the value of field awr_id
     *
     * @return integer
     */
    public function getAwrId()
    {
        return $this->awr_id;
    }

    /**
     * Returns the value of field method
     *
     * @return integer
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Returns the value of field type
     *
     * @return integer
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Returns the value of field description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Returns the value of field mobile
     *
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     * Returns the value of field longitude
     *
     * @return string
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * Returns the value of field latitude
     *
     * @return string
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * Returns the value of field points
     *
     * @return integer
     */
    public function getPoints()
    {
        return $this->points;
    }

    /**
     * Returns the value of field updates
     *
     * @return integer
     */
    public function getUpdates()
    {
        return $this->updates;
    }

    /**
     * Returns the value of field update_desc
     *
     * @return string
     */
    public function getUpdateDesc()
    {
        return $this->update_desc;
    }

    /**
     * Returns the value of field status
     *
     * @return integer
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Returns the value of field awr_time
     *
     * @return string
     */
    public function getAwrTime()
    {
        return $this->awr_time;
    }

    /**
     * Returns the value of field awr_cancel_time
     *
     * @return string
     */
    public function getAwrCancelTime()
    {
        return $this->awr_cancel_time;
    }

    /**
     * Returns the value of field awr_fin_time
     *
     * @return string
     */
    public function getAwrFinTime()
    {
        return $this->awr_fin_time;
    }

    /**
     * Returns the value of field created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Returns the value of field updated_at
     *
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'appeals';
    }

}
