<?php

namespace Ddb\Models;

/**
 * AppealAnswers
 * 
 * @package Ddb\Models
 * @autogenerated by Phalcon Developer Utils
 * @date 2018-04-25, 13:10:51
 * 
 * @method static static findFirstByAppealId($appeal_id)
 * @method static static[] findByAppealId($appeal_id)
 * @method static int countByAppealId($appeal_id)
 * @method static static findFirstByAwrId($awr_id)
 * @method static static[] findByAwrId($awr_id)
 * @method static int countByAwrId($awr_id)
 * @method static static findFirstByType($type)
 * @method static static[] findByType($type)
 * @method static int countByType($type)
 * @method static static findFirstByCancelReason($cancel_reason)
 * @method static static[] findByCancelReason($cancel_reason)
 * @method static int countByCancelReason($cancel_reason)
 * @method static static findFirstByCancelTime($cancel_time)
 * @method static static[] findByCancelTime($cancel_time)
 * @method static int countByCancelTime($cancel_time)
 * @method static static findFirstByFinishTime($finish_time)
 * @method static static[] findByFinishTime($finish_time)
 * @method static int countByFinishTime($finish_time)
 * @method static static findFirstByCreatedAt($created_at)
 * @method static static[] findByCreatedAt($created_at)
 * @method static int countByCreatedAt($created_at)
 * @method static static findFirstByUpdatedAt($updated_at)
 * @method static static[] findByUpdatedAt($updated_at)
 * @method static int countByUpdatedAt($updated_at)
 */
class AppealAnswers extends BaseModel
{

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var integer
     */
    protected $appeal_id;

    /**
     *
     * @var integer
     */
    protected $awr_id;

    /**
     *
     * @var integer
     */
    protected $type;

    /**
     *
     * @var integer
     */
    protected $status;

    /**
     *
     * @var string
     */
    protected $cancel_reason;

    /**
     *
     * @var string
     */
    protected $cancel_time;

    /**
     *
     * @var string
     */
    protected $finish_time;

    /**
     *
     * @var string
     */
    protected $created_at;

    /**
     *
     * @var string
     */
    protected $updated_at;

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return static
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field appeal_id
     *
     * @param integer $appeal_id
     * @return static
     */
    public function setAppealId($appeal_id)
    {
        $this->appeal_id = $appeal_id;

        return $this;
    }

    /**
     * Method to set the value of field awr_id
     *
     * @param integer $awr_id
     * @return static
     */
    public function setAwrId($awr_id)
    {
        $this->awr_id = $awr_id;

        return $this;
    }

    /**
     * Method to set the value of field type
     *
     * @param integer $type
     * @return static
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Method to set the value of field status
     *
     * @param integer $status
     * @return static
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Method to set the value of field cancel_reason
     *
     * @param string $cancel_reason
     * @return static
     */
    public function setCancelReason($cancel_reason)
    {
        $this->cancel_reason = $cancel_reason;

        return $this;
    }

    /**
     * Method to set the value of field cancel_time
     *
     * @param string $cancel_time
     * @return static
     */
    public function setCancelTime($cancel_time)
    {
        $this->cancel_time = $cancel_time;

        return $this;
    }

    /**
     * Method to set the value of field finish_time
     *
     * @param string $finish_time
     * @return static
     */
    public function setFinishTime($finish_time)
    {
        $this->finish_time = $finish_time;

        return $this;
    }

    /**
     * Method to set the value of field created_at
     *
     * @param string $created_at
     * @return static
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Method to set the value of field updated_at
     *
     * @param string $updated_at
     * @return static
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field appeal_id
     *
     * @return integer
     */
    public function getAppealId()
    {
        return $this->appeal_id;
    }

    /**
     * Returns the value of field awr_id
     *
     * @return integer
     */
    public function getAwrId()
    {
        return $this->awr_id;
    }

    /**
     * Returns the value of field type
     *
     * @return integer
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Returns the value of field status
     *
     * @return integer
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Returns the value of field cancel_reason
     *
     * @return string
     */
    public function getCancelReason()
    {
        return $this->cancel_reason;
    }

    /**
     * Returns the value of field cancel_time
     *
     * @return string
     */
    public function getCancelTime()
    {
        return $this->cancel_time;
    }

    /**
     * Returns the value of field finish_time
     *
     * @return string
     */
    public function getFinishTime()
    {
        return $this->finish_time;
    }

    /**
     * Returns the value of field created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Returns the value of field updated_at
     *
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'appeal_answers';
    }

}
