<?php

namespace Ddb\Models;

/**
 * Areas
 * 
 * @package Ddb\Models
 * @autogenerated by Phalcon Developer Utils
 * @date 2018-04-25, 13:10:51
 * 
 * @method static static findFirstByDistrictCode($district_code)
 * @method static static[] findByDistrictCode($district_code)
 * @method static int countByDistrictCode($district_code)
 * @method static static findFirstByDistrictName($district_name)
 * @method static static[] findByDistrictName($district_name)
 * @method static int countByDistrictName($district_name)
 * @method static static findFirstByCityCode($city_code)
 * @method static static[] findByCityCode($city_code)
 * @method static int countByCityCode($city_code)
 * @method static static findFirstByCityName($city_name)
 * @method static static[] findByCityName($city_name)
 * @method static int countByCityName($city_name)
 * @method static static findFirstByProvinceCode($province_code)
 * @method static static[] findByProvinceCode($province_code)
 * @method static int countByProvinceCode($province_code)
 * @method static static findFirstByProvinceName($province_name)
 * @method static static[] findByProvinceName($province_name)
 * @method static int countByProvinceName($province_name)
 */
class Areas extends BaseModel
{

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var string
     */
    protected $district_code;

    /**
     *
     * @var string
     */
    protected $district_name;

    /**
     *
     * @var string
     */
    protected $city_code;

    /**
     *
     * @var string
     */
    protected $city_name;

    /**
     *
     * @var string
     */
    protected $province_code;

    /**
     *
     * @var string
     */
    protected $province_name;

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return static
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field district_code
     *
     * @param string $district_code
     * @return static
     */
    public function setDistrictCode($district_code)
    {
        $this->district_code = $district_code;

        return $this;
    }

    /**
     * Method to set the value of field district_name
     *
     * @param string $district_name
     * @return static
     */
    public function setDistrictName($district_name)
    {
        $this->district_name = $district_name;

        return $this;
    }

    /**
     * Method to set the value of field city_code
     *
     * @param string $city_code
     * @return static
     */
    public function setCityCode($city_code)
    {
        $this->city_code = $city_code;

        return $this;
    }

    /**
     * Method to set the value of field city_name
     *
     * @param string $city_name
     * @return static
     */
    public function setCityName($city_name)
    {
        $this->city_name = $city_name;

        return $this;
    }

    /**
     * Method to set the value of field province_code
     *
     * @param string $province_code
     * @return static
     */
    public function setProvinceCode($province_code)
    {
        $this->province_code = $province_code;

        return $this;
    }

    /**
     * Method to set the value of field province_name
     *
     * @param string $province_name
     * @return static
     */
    public function setProvinceName($province_name)
    {
        $this->province_name = $province_name;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field district_code
     *
     * @return string
     */
    public function getDistrictCode()
    {
        return $this->district_code;
    }

    /**
     * Returns the value of field district_name
     *
     * @return string
     */
    public function getDistrictName()
    {
        return $this->district_name;
    }

    /**
     * Returns the value of field city_code
     *
     * @return string
     */
    public function getCityCode()
    {
        return $this->city_code;
    }

    /**
     * Returns the value of field city_name
     *
     * @return string
     */
    public function getCityName()
    {
        return $this->city_name;
    }

    /**
     * Returns the value of field province_code
     *
     * @return string
     */
    public function getProvinceCode()
    {
        return $this->province_code;
    }

    /**
     * Returns the value of field province_name
     *
     * @return string
     */
    public function getProvinceName()
    {
        return $this->province_name;
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'areas';
    }

}
