<?php

namespace Ddb\Models;

/**
 * MemberSigns
 * 
 * @package Ddb\Models
 * @autogenerated by Phalcon Developer Utils
 * @date 2018-10-25, 01:03:51
 * 
 * @method static static findFirstByMemberId($member_id)
 * @method static static[] findByMemberId($member_id)
 * @method static int countByMemberId($member_id)
 * @method static static findFirstByDay($day)
 * @method static static[] findByDay($day)
 * @method static int countByDay($day)
 * @method static static findFirstByWeek($week)
 * @method static static[] findByWeek($week)
 * @method static int countByWeek($week)
 * @method static static findFirstByWeekCount($week_count)
 * @method static static[] findByWeekCount($week_count)
 * @method static int countByWeekCount($week_count)
 * @method static static findFirstByMonthCount($month_count)
 * @method static static[] findByMonthCount($month_count)
 * @method static int countByMonthCount($month_count)
 * @method static static findFirstByContinueCount($continue_count)
 * @method static static[] findByContinueCount($continue_count)
 * @method static int countByContinueCount($continue_count)
 * @method static static findFirstByCount($count)
 * @method static static[] findByCount($count)
 * @method static int countByCount($count)
 * @method static static findFirstByCreatedAt($created_at)
 * @method static static[] findByCreatedAt($created_at)
 * @method static int countByCreatedAt($created_at)
 * @method static static findFirstByUpdatedAt($updated_at)
 * @method static static[] findByUpdatedAt($updated_at)
 * @method static int countByUpdatedAt($updated_at)
 */
class MemberSigns extends BaseModel
{

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var integer
     */
    protected $member_id;

    /**
     *
     * @var string
     */
    protected $day;

    /**
     *
     * @var integer
     */
    protected $week;

    /**
     *
     * @var integer
     */
    protected $week_count;

    /**
     *
     * @var integer
     */
    protected $month_count;

    /**
     *
     * @var integer
     */
    protected $continue_count;

    /**
     *
     * @var integer
     */
    protected $count;

    /**
     *
     * @var string
     */
    protected $created_at;

    /**
     *
     * @var string
     */
    protected $updated_at;

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return static
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field member_id
     *
     * @param integer $member_id
     * @return static
     */
    public function setMemberId($member_id)
    {
        $this->member_id = $member_id;

        return $this;
    }

    /**
     * Method to set the value of field day
     *
     * @param string $day
     * @return static
     */
    public function setDay($day)
    {
        $this->day = $day;

        return $this;
    }

    /**
     * Method to set the value of field week
     *
     * @param integer $week
     * @return static
     */
    public function setWeek($week)
    {
        $this->week = $week;

        return $this;
    }

    /**
     * Method to set the value of field week_count
     *
     * @param integer $week_count
     * @return static
     */
    public function setWeekCount($week_count)
    {
        $this->week_count = $week_count;

        return $this;
    }

    /**
     * Method to set the value of field month_count
     *
     * @param integer $month_count
     * @return static
     */
    public function setMonthCount($month_count)
    {
        $this->month_count = $month_count;

        return $this;
    }

    /**
     * Method to set the value of field continue_count
     *
     * @param integer $continue_count
     * @return static
     */
    public function setContinueCount($continue_count)
    {
        $this->continue_count = $continue_count;

        return $this;
    }

    /**
     * Method to set the value of field count
     *
     * @param integer $count
     * @return static
     */
    public function setCount($count)
    {
        $this->count = $count;

        return $this;
    }

    /**
     * Method to set the value of field created_at
     *
     * @param string $created_at
     * @return static
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Method to set the value of field updated_at
     *
     * @param string $updated_at
     * @return static
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field member_id
     *
     * @return integer
     */
    public function getMemberId()
    {
        return $this->member_id;
    }

    /**
     * Returns the value of field day
     *
     * @return string
     */
    public function getDay()
    {
        return $this->day;
    }

    /**
     * Returns the value of field week
     *
     * @return integer
     */
    public function getWeek()
    {
        return $this->week;
    }

    /**
     * Returns the value of field week_count
     *
     * @return integer
     */
    public function getWeekCount()
    {
        return $this->week_count;
    }

    /**
     * Returns the value of field month_count
     *
     * @return integer
     */
    public function getMonthCount()
    {
        return $this->month_count;
    }

    /**
     * Returns the value of field continue_count
     *
     * @return integer
     */
    public function getContinueCount()
    {
        return $this->continue_count;
    }

    /**
     * Returns the value of field count
     *
     * @return integer
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Returns the value of field created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Returns the value of field updated_at
     *
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'member_signs';
    }

}
