<?php

namespace Ddb\Models;

/**
 * Members
 * 
 * @package Ddb\Models
 * @autogenerated by Phalcon Developer Utils
 * @date 2018-04-25, 17:30:25
 * 
 * @method static static findFirstByAvatarurl($avatarUrl)
 * @method static static[] findByAvatarurl($avatarUrl)
 * @method static int countByAvatarurl($avatarUrl)
 * @method static static findFirstByProvince($province)
 * @method static static[] findByProvince($province)
 * @method static int countByProvince($province)
 * @method static static findFirstByCity($city)
 * @method static static[] findByCity($city)
 * @method static int countByCity($city)
 * @method static static findFirstByDistrict($district)
 * @method static static[] findByDistrict($district)
 * @method static int countByDistrict($district)
 * @method static static findFirstByCountry($country)
 * @method static static[] findByCountry($country)
 * @method static int countByCountry($country)
 * @method static static findFirstByLanguage($language)
 * @method static static[] findByLanguage($language)
 * @method static int countByLanguage($language)
 * @method static static findFirstByGender($gender)
 * @method static static[] findByGender($gender)
 * @method static int countByGender($gender)
 * @method static static findFirstByNickname($nickName)
 * @method static static[] findByNickname($nickName)
 * @method static int countByNickname($nickName)
 * @method static static findFirstByMobile($mobile)
 * @method static static[] findByMobile($mobile)
 * @method static int countByMobile($mobile)
 * @method static static findFirstByPoints($points)
 * @method static static[] findByPoints($points)
 * @method static int countByPoints($points)
 * @method static static findFirstByType($type)
 * @method static static[] findByType($type)
 * @method static int countByType($type)
 * @method static static findFirstByAuthTime($auth_time)
 * @method static static[] findByAuthTime($auth_time)
 * @method static int countByAuthTime($auth_time)
 * @method static static findFirstByToken($token)
 * @method static static[] findByToken($token)
 * @method static int countByToken($token)
 * @method static static findFirstByTokenTime($token_time)
 * @method static static[] findByTokenTime($token_time)
 * @method static int countByTokenTime($token_time)
 * @method static static findFirstBySceneCode($scene_code)
 * @method static static[] findBySceneCode($scene_code)
 * @method static int countBySceneCode($scene_code)
 * @method static static findFirstByOpenId($open_id)
 * @method static static[] findByOpenId($open_id)
 * @method static int countByOpenId($open_id)
 * @method static static findFirstByCreatedAt($created_at)
 * @method static static[] findByCreatedAt($created_at)
 * @method static int countByCreatedAt($created_at)
 * @method static static findFirstByUpdatedAt($updated_at)
 * @method static static[] findByUpdatedAt($updated_at)
 * @method static int countByUpdatedAt($updated_at)
 */
abstract class Members extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var string
     */
    protected $avatarUrl;

    /**
     *
     * @var string
     */
    protected $province;

    /**
     *
     * @var string
     */
    protected $city;

    /**
     *
     * @var string
     */
    protected $district;

    /**
     *
     * @var string
     */
    protected $country;

    /**
     *
     * @var string
     */
    protected $language;

    /**
     *
     * @var integer
     */
    protected $gender;

    /**
     *
     * @var string
     */
    protected $nickName;

    /**
     *
     * @var string
     */
    protected $mobile;

    /**
     *
     * @var string
     */
    protected $points;

    /**
     *
     * @var integer
     */
    protected $type;

    /**
     *
     * @var string
     */
    protected $auth_time;

    /**
     *
     * @var string
     */
    protected $token;

    /**
     *
     * @var string
     */
    protected $token_time;

    /**
     *
     * @var string
     */
    protected $scene_code;

    /**
     *
     * @var string
     */
    protected $open_id;

    /**
     *
     * @var string
     */
    protected $created_at;

    /**
     *
     * @var string
     */
    protected $updated_at;

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return static
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field avatarUrl
     *
     * @param string $avatarUrl
     * @return static
     */
    public function setAvatarurl($avatarUrl)
    {
        $this->avatarUrl = $avatarUrl;

        return $this;
    }

    /**
     * Method to set the value of field province
     *
     * @param string $province
     * @return static
     */
    public function setProvince($province)
    {
        $this->province = $province;

        return $this;
    }

    /**
     * Method to set the value of field city
     *
     * @param string $city
     * @return static
     */
    public function setCity($city)
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Method to set the value of field district
     *
     * @param string $district
     * @return static
     */
    public function setDistrict($district)
    {
        $this->district = $district;

        return $this;
    }

    /**
     * Method to set the value of field country
     *
     * @param string $country
     * @return static
     */
    public function setCountry($country)
    {
        $this->country = $country;

        return $this;
    }

    /**
     * Method to set the value of field language
     *
     * @param string $language
     * @return static
     */
    public function setLanguage($language)
    {
        $this->language = $language;

        return $this;
    }

    /**
     * Method to set the value of field gender
     *
     * @param integer $gender
     * @return static
     */
    public function setGender($gender)
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * Method to set the value of field nickName
     *
     * @param string $nickName
     * @return static
     */
    public function setNickname($nickName)
    {
        $this->nickName = $nickName;

        return $this;
    }

    /**
     * Method to set the value of field mobile
     *
     * @param string $mobile
     * @return static
     */
    public function setMobile($mobile)
    {
        $this->mobile = $mobile;

        return $this;
    }

    /**
     * Method to set the value of field points
     *
     * @param string $points
     * @return static
     */
    public function setPoints($points)
    {
        $this->points = $points;

        return $this;
    }

    /**
     * Method to set the value of field type
     *
     * @param integer $type
     * @return static
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Method to set the value of field auth_time
     *
     * @param string $auth_time
     * @return static
     */
    public function setAuthTime($auth_time)
    {
        $this->auth_time = $auth_time;

        return $this;
    }

    /**
     * Method to set the value of field token
     *
     * @param string $token
     * @return static
     */
    public function setToken($token)
    {
        $this->token = $token;

        return $this;
    }

    /**
     * Method to set the value of field token_time
     *
     * @param string $token_time
     * @return static
     */
    public function setTokenTime($token_time)
    {
        $this->token_time = $token_time;

        return $this;
    }

    /**
     * Method to set the value of field scene_code
     *
     * @param string $scene_code
     * @return static
     */
    public function setSceneCode($scene_code)
    {
        $this->scene_code = $scene_code;

        return $this;
    }

    /**
     * Method to set the value of field open_id
     *
     * @param string $open_id
     * @return static
     */
    public function setOpenId($open_id)
    {
        $this->open_id = $open_id;

        return $this;
    }

    /**
     * Method to set the value of field created_at
     *
     * @param string $created_at
     * @return static
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Method to set the value of field updated_at
     *
     * @param string $updated_at
     * @return static
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field avatarUrl
     *
     * @return string
     */
    public function getAvatarurl()
    {
        return $this->avatarUrl;
    }

    /**
     * Returns the value of field province
     *
     * @return string
     */
    public function getProvince()
    {
        return $this->province;
    }

    /**
     * Returns the value of field city
     *
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Returns the value of field district
     *
     * @return string
     */
    public function getDistrict()
    {
        return $this->district;
    }

    /**
     * Returns the value of field country
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Returns the value of field language
     *
     * @return string
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Returns the value of field gender
     *
     * @return integer
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * Returns the value of field nickName
     *
     * @return string
     */
    public function getNickname()
    {
        return $this->nickName;
    }

    /**
     * Returns the value of field mobile
     *
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     * Returns the value of field points
     *
     * @return string
     */
    public function getPoints()
    {
        return $this->points;
    }

    /**
     * Returns the value of field type
     *
     * @return integer
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Returns the value of field auth_time
     *
     * @return string
     */
    public function getAuthTime()
    {
        return $this->auth_time;
    }

    /**
     * Returns the value of field token
     *
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Returns the value of field token_time
     *
     * @return string
     */
    public function getTokenTime()
    {
        return $this->token_time;
    }

    /**
     * Returns the value of field scene_code
     *
     * @return string
     */
    public function getSceneCode()
    {
        return $this->scene_code;
    }

    /**
     * Returns the value of field open_id
     *
     * @return string
     */
    public function getOpenId()
    {
        return $this->open_id;
    }

    /**
     * Returns the value of field created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Returns the value of field updated_at
     *
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'members';
    }

}
