<?php

namespace Ddb\Models;

/**
 * MemberBikes
 * 
 * @package Ddb\Models
 * @autogenerated by Phalcon Developer Utils
 * @date 2018-05-04, 17:36:46
 * 
 * @method static static findFirstByMemberId($member_id)
 * @method static static[] findByMemberId($member_id)
 * @method static int countByMemberId($member_id)
 * @method static static findFirstByBuyDate($buy_date)
 * @method static static[] findByBuyDate($buy_date)
 * @method static int countByBuyDate($buy_date)
 * @method static static findFirstByVoltage($voltage)
 * @method static static[] findByVoltage($voltage)
 * @method static int countByVoltage($voltage)
 * @method static static findFirstByBrandId($brand_id)
 * @method static static[] findByBrandId($brand_id)
 * @method static int countByBrandId($brand_id)
 * @method static static findFirstByBrandName($brand_name)
 * @method static static[] findByBrandName($brand_name)
 * @method static int countByBrandName($brand_name)
 * @method static static findFirstByPrice($price)
 * @method static static[] findByPrice($price)
 * @method static int countByPrice($price)
 * @method static static findFirstByLastChangeTime($last_change_time)
 * @method static static[] findByLastChangeTime($last_change_time)
 * @method static int countByLastChangeTime($last_change_time)
 * @method static static findFirstByNumber($number)
 * @method static static[] findByNumber($number)
 * @method static int countByNumber($number)
 * @method static static findFirstByCreatedAt($created_at)
 * @method static static[] findByCreatedAt($created_at)
 * @method static int countByCreatedAt($created_at)
 * @method static static findFirstByUpdatedAt($updated_at)
 * @method static static[] findByUpdatedAt($updated_at)
 * @method static int countByUpdatedAt($updated_at)
 */
class MemberBikes extends BaseModel
{

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var integer
     */
    protected $member_id;

    /**
     *
     * @var string
     */
    protected $buy_date;

    /**
     *
     * @var integer
     */
    protected $voltage;

    /**
     *
     * @var integer
     */
    protected $brand_id;

    /**
     *
     * @var string
     */
    protected $brand_name;

    /**
     *
     * @var double
     */
    protected $price;

    /**
     *
     * @var integer
     */
    protected $status;

    /**
     *
     * @var string
     */
    protected $last_change_time;

    /**
     *
     * @var string
     */
    protected $number;

    /**
     *
     * @var string
     */
    protected $created_at;

    /**
     *
     * @var string
     */
    protected $updated_at;

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return static
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field member_id
     *
     * @param integer $member_id
     * @return static
     */
    public function setMemberId($member_id)
    {
        $this->member_id = $member_id;

        return $this;
    }

    /**
     * Method to set the value of field buy_date
     *
     * @param string $buy_date
     * @return static
     */
    public function setBuyDate($buy_date)
    {
        $this->buy_date = $buy_date;

        return $this;
    }

    /**
     * Method to set the value of field voltage
     *
     * @param integer $voltage
     * @return static
     */
    public function setVoltage($voltage)
    {
        $this->voltage = $voltage;

        return $this;
    }

    /**
     * Method to set the value of field brand_id
     *
     * @param integer $brand_id
     * @return static
     */
    public function setBrandId($brand_id)
    {
        $this->brand_id = $brand_id;

        return $this;
    }

    /**
     * Method to set the value of field brand_name
     *
     * @param string $brand_name
     * @return static
     */
    public function setBrandName($brand_name)
    {
        $this->brand_name = $brand_name;

        return $this;
    }

    /**
     * Method to set the value of field price
     *
     * @param double $price
     * @return static
     */
    public function setPrice($price)
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Method to set the value of field status
     *
     * @param integer $status
     * @return static
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Method to set the value of field last_change_time
     *
     * @param string $last_change_time
     * @return static
     */
    public function setLastChangeTime($last_change_time)
    {
        $this->last_change_time = $last_change_time;

        return $this;
    }

    /**
     * Method to set the value of field number
     *
     * @param string $number
     * @return static
     */
    public function setNumber($number)
    {
        $this->number = $number;

        return $this;
    }

    /**
     * Method to set the value of field created_at
     *
     * @param string $created_at
     * @return static
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Method to set the value of field updated_at
     *
     * @param string $updated_at
     * @return static
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field member_id
     *
     * @return integer
     */
    public function getMemberId()
    {
        return $this->member_id;
    }

    /**
     * Returns the value of field buy_date
     *
     * @return string
     */
    public function getBuyDate()
    {
        return $this->buy_date;
    }

    /**
     * Returns the value of field voltage
     *
     * @return integer
     */
    public function getVoltage()
    {
        return $this->voltage;
    }

    /**
     * Returns the value of field brand_id
     *
     * @return integer
     */
    public function getBrandId()
    {
        return $this->brand_id;
    }

    /**
     * Returns the value of field brand_name
     *
     * @return string
     */
    public function getBrandName()
    {
        return $this->brand_name;
    }

    /**
     * Returns the value of field price
     *
     * @return double
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Returns the value of field status
     *
     * @return integer
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Returns the value of field last_change_time
     *
     * @return string
     */
    public function getLastChangeTime()
    {
        return $this->last_change_time;
    }

    /**
     * Returns the value of field number
     *
     * @return string
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * Returns the value of field created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Returns the value of field updated_at
     *
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'member_bikes';
    }

}
