<?php

namespace Ddb\Models;

/**
 * MemberPoints
 * 
 * @package Ddb\Models
 * @autogenerated by Phalcon Developer Utils
 * @date 2018-10-14, 17:28:14
 * 
 * @method static static findFirstByMemberId($member_id)
 * @method static static[] findByMemberId($member_id)
 * @method static int countByMemberId($member_id)
 * @method static static findFirstByType($type)
 * @method static static[] findByType($type)
 * @method static int countByType($type)
 * @method static static findFirstByValue($value)
 * @method static static[] findByValue($value)
 * @method static int countByValue($value)
 * @method static static findFirstBySecondBikeId($second_bike_id)
 * @method static static[] findBySecondBikeId($second_bike_id)
 * @method static int countBySecondBikeId($second_bike_id)
 * @method static static findFirstByAppealId($appeal_id)
 * @method static static[] findByAppealId($appeal_id)
 * @method static int countByAppealId($appeal_id)
 * @method static static findFirstByLostBikeId($lost_bike_id)
 * @method static static[] findByLostBikeId($lost_bike_id)
 * @method static int countByLostBikeId($lost_bike_id)
 * @method static static findFirstByNewBikeId($new_bike_id)
 * @method static static[] findByNewBikeId($new_bike_id)
 * @method static int countByNewBikeId($new_bike_id)
 * @method static static findFirstByCreatedAt($created_at)
 * @method static static[] findByCreatedAt($created_at)
 * @method static int countByCreatedAt($created_at)
 * @method static static findFirstByUpdatedAt($updated_at)
 * @method static static[] findByUpdatedAt($updated_at)
 * @method static int countByUpdatedAt($updated_at)
 */
class MemberPoints extends BaseModel
{

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var integer
     */
    protected $member_id;

    /**
     *
     * @var integer
     */
    protected $type;

    /**
     *
     * @var integer
     */
    protected $value;

    /**
     *
     * @var integer
     */
    protected $second_bike_id;

    /**
     *
     * @var integer
     */
    protected $appeal_id;

    /**
     *
     * @var integer
     */
    protected $lost_bike_id;

    /**
     *
     * @var integer
     */
    protected $new_bike_id;

    /**
     *
     * @var string
     */
    protected $created_at;

    /**
     *
     * @var string
     */
    protected $updated_at;

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return static
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field member_id
     *
     * @param integer $member_id
     * @return static
     */
    public function setMemberId($member_id)
    {
        $this->member_id = $member_id;

        return $this;
    }

    /**
     * Method to set the value of field type
     *
     * @param integer $type
     * @return static
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Method to set the value of field value
     *
     * @param integer $value
     * @return static
     */
    public function setValue($value)
    {
        $this->value = $value;

        return $this;
    }

    /**
     * Method to set the value of field second_bike_id
     *
     * @param integer $second_bike_id
     * @return static
     */
    public function setSecondBikeId($second_bike_id)
    {
        $this->second_bike_id = $second_bike_id;

        return $this;
    }

    /**
     * Method to set the value of field appeal_id
     *
     * @param integer $appeal_id
     * @return static
     */
    public function setAppealId($appeal_id)
    {
        $this->appeal_id = $appeal_id;

        return $this;
    }

    /**
     * Method to set the value of field lost_bike_id
     *
     * @param integer $lost_bike_id
     * @return static
     */
    public function setLostBikeId($lost_bike_id)
    {
        $this->lost_bike_id = $lost_bike_id;

        return $this;
    }

    /**
     * Method to set the value of field new_bike_id
     *
     * @param integer $new_bike_id
     * @return static
     */
    public function setNewBikeId($new_bike_id)
    {
        $this->new_bike_id = $new_bike_id;

        return $this;
    }

    /**
     * Method to set the value of field created_at
     *
     * @param string $created_at
     * @return static
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Method to set the value of field updated_at
     *
     * @param string $updated_at
     * @return static
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field member_id
     *
     * @return integer
     */
    public function getMemberId()
    {
        return $this->member_id;
    }

    /**
     * Returns the value of field type
     *
     * @return integer
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Returns the value of field value
     *
     * @return integer
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Returns the value of field second_bike_id
     *
     * @return integer
     */
    public function getSecondBikeId()
    {
        return $this->second_bike_id;
    }

    /**
     * Returns the value of field appeal_id
     *
     * @return integer
     */
    public function getAppealId()
    {
        return $this->appeal_id;
    }

    /**
     * Returns the value of field lost_bike_id
     *
     * @return integer
     */
    public function getLostBikeId()
    {
        return $this->lost_bike_id;
    }

    /**
     * Returns the value of field new_bike_id
     *
     * @return integer
     */
    public function getNewBikeId()
    {
        return $this->new_bike_id;
    }

    /**
     * Returns the value of field created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Returns the value of field updated_at
     *
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'member_points';
    }

}
