<?php

namespace Ddb\Models;

/**
 * NewBikes
 * 
 * @package Ddb\Models
 * @autogenerated by Phalcon Developer Utils
 * @date 2018-10-21, 23:54:47
 * 
 * @method static static findFirstByMemberId($member_id)
 * @method static static[] findByMemberId($member_id)
 * @method static int countByMemberId($member_id)
 * @method static static findFirstByVoltage($voltage)
 * @method static static[] findByVoltage($voltage)
 * @method static int countByVoltage($voltage)
 * @method static static findFirstByBrandId($brand_id)
 * @method static static[] findByBrandId($brand_id)
 * @method static int countByBrandId($brand_id)
 * @method static static findFirstByBrandName($brand_name)
 * @method static static[] findByBrandName($brand_name)
 * @method static int countByBrandName($brand_name)
 * @method static static findFirstByPrice($price)
 * @method static static[] findByPrice($price)
 * @method static int countByPrice($price)
 * @method static static findFirstByBatteryBrand($battery_brand)
 * @method static static[] findByBatteryBrand($battery_brand)
 * @method static int countByBatteryBrand($battery_brand)
 * @method static static findFirstByDistance($distance)
 * @method static static[] findByDistance($distance)
 * @method static int countByDistance($distance)
 * @method static static findFirstByGuaranteePeriod($guarantee_period)
 * @method static static[] findByGuaranteePeriod($guarantee_period)
 * @method static int countByGuaranteePeriod($guarantee_period)
 * @method static static findFirstByAvailTime($avail_time)
 * @method static static[] findByAvailTime($avail_time)
 * @method static int countByAvailTime($avail_time)
 * @method static static findFirstByProvince($province)
 * @method static static[] findByProvince($province)
 * @method static int countByProvince($province)
 * @method static static findFirstByCity($city)
 * @method static static[] findByCity($city)
 * @method static int countByCity($city)
 * @method static static findFirstByDistrict($district)
 * @method static static[] findByDistrict($district)
 * @method static int countByDistrict($district)
 * @method static static findFirstByProvinceCode($province_code)
 * @method static static[] findByProvinceCode($province_code)
 * @method static int countByProvinceCode($province_code)
 * @method static static findFirstByCityCode($city_code)
 * @method static static[] findByCityCode($city_code)
 * @method static int countByCityCode($city_code)
 * @method static static findFirstByDistrictCode($district_code)
 * @method static static[] findByDistrictCode($district_code)
 * @method static int countByDistrictCode($district_code)
 * @method static static findFirstByDetailAddr($detail_addr)
 * @method static static[] findByDetailAddr($detail_addr)
 * @method static int countByDetailAddr($detail_addr)
 * @method static static findFirstByRemark($remark)
 * @method static static[] findByRemark($remark)
 * @method static int countByRemark($remark)
 * @method static static findFirstByRefuseReason($refuse_reason)
 * @method static static[] findByRefuseReason($refuse_reason)
 * @method static int countByRefuseReason($refuse_reason)
 * @method static static findFirstByCancelTime($cancel_time)
 * @method static static[] findByCancelTime($cancel_time)
 * @method static int countByCancelTime($cancel_time)
 * @method static static findFirstByCancelReason($cancel_reason)
 * @method static static[] findByCancelReason($cancel_reason)
 * @method static int countByCancelReason($cancel_reason)
 * @method static static findFirstByCreatedAt($created_at)
 * @method static static[] findByCreatedAt($created_at)
 * @method static int countByCreatedAt($created_at)
 * @method static static findFirstByUpdatedAt($updated_at)
 * @method static static[] findByUpdatedAt($updated_at)
 * @method static int countByUpdatedAt($updated_at)
 */
class NewBikes extends BaseModel
{

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var integer
     */
    protected $member_id;

    /**
     *
     * @var integer
     */
    protected $voltage;

    /**
     *
     * @var integer
     */
    protected $brand_id;

    /**
     *
     * @var string
     */
    protected $brand_name;

    /**
     *
     * @var double
     */
    protected $price;

    /**
     *
     * @var string
     */
    protected $battery_brand;

    /**
     *
     * @var integer
     */
    protected $distance;

    /**
     *
     * @var integer
     */
    protected $guarantee_period;

    /**
     *
     * @var string
     */
    protected $avail_time;

    /**
     *
     * @var string
     */
    protected $province;

    /**
     *
     * @var string
     */
    protected $city;

    /**
     *
     * @var string
     */
    protected $district;

    /**
     *
     * @var string
     */
    protected $province_code;

    /**
     *
     * @var string
     */
    protected $city_code;

    /**
     *
     * @var string
     */
    protected $district_code;

    /**
     *
     * @var string
     */
    protected $detail_addr;

    /**
     *
     * @var string
     */
    protected $remark;

    /**
     *
     * @var integer
     */
    protected $status;

    /**
     *
     * @var string
     */
    protected $refuse_reason;

    /**
     *
     * @var string
     */
    protected $cancel_time;

    /**
     *
     * @var string
     */
    protected $cancel_reason;

    /**
     *
     * @var string
     */
    protected $created_at;

    /**
     *
     * @var string
     */
    protected $updated_at;

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return static
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field member_id
     *
     * @param integer $member_id
     * @return static
     */
    public function setMemberId($member_id)
    {
        $this->member_id = $member_id;

        return $this;
    }

    /**
     * Method to set the value of field voltage
     *
     * @param integer $voltage
     * @return static
     */
    public function setVoltage($voltage)
    {
        $this->voltage = $voltage;

        return $this;
    }

    /**
     * Method to set the value of field brand_id
     *
     * @param integer $brand_id
     * @return static
     */
    public function setBrandId($brand_id)
    {
        $this->brand_id = $brand_id;

        return $this;
    }

    /**
     * Method to set the value of field brand_name
     *
     * @param string $brand_name
     * @return static
     */
    public function setBrandName($brand_name)
    {
        $this->brand_name = $brand_name;

        return $this;
    }

    /**
     * Method to set the value of field price
     *
     * @param double $price
     * @return static
     */
    public function setPrice($price)
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Method to set the value of field battery_brand
     *
     * @param string $battery_brand
     * @return static
     */
    public function setBatteryBrand($battery_brand)
    {
        $this->battery_brand = $battery_brand;

        return $this;
    }

    /**
     * Method to set the value of field distance
     *
     * @param integer $distance
     * @return static
     */
    public function setDistance($distance)
    {
        $this->distance = $distance;

        return $this;
    }

    /**
     * Method to set the value of field guarantee_period
     *
     * @param integer $guarantee_period
     * @return static
     */
    public function setGuaranteePeriod($guarantee_period)
    {
        $this->guarantee_period = $guarantee_period;

        return $this;
    }

    /**
     * Method to set the value of field avail_time
     *
     * @param string $avail_time
     * @return static
     */
    public function setAvailTime($avail_time)
    {
        $this->avail_time = $avail_time;

        return $this;
    }

    /**
     * Method to set the value of field province
     *
     * @param string $province
     * @return static
     */
    public function setProvince($province)
    {
        $this->province = $province;

        return $this;
    }

    /**
     * Method to set the value of field city
     *
     * @param string $city
     * @return static
     */
    public function setCity($city)
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Method to set the value of field district
     *
     * @param string $district
     * @return static
     */
    public function setDistrict($district)
    {
        $this->district = $district;

        return $this;
    }

    /**
     * Method to set the value of field province_code
     *
     * @param string $province_code
     * @return static
     */
    public function setProvinceCode($province_code)
    {
        $this->province_code = $province_code;

        return $this;
    }

    /**
     * Method to set the value of field city_code
     *
     * @param string $city_code
     * @return static
     */
    public function setCityCode($city_code)
    {
        $this->city_code = $city_code;

        return $this;
    }

    /**
     * Method to set the value of field district_code
     *
     * @param string $district_code
     * @return static
     */
    public function setDistrictCode($district_code)
    {
        $this->district_code = $district_code;

        return $this;
    }

    /**
     * Method to set the value of field detail_addr
     *
     * @param string $detail_addr
     * @return static
     */
    public function setDetailAddr($detail_addr)
    {
        $this->detail_addr = $detail_addr;

        return $this;
    }

    /**
     * Method to set the value of field remark
     *
     * @param string $remark
     * @return static
     */
    public function setRemark($remark)
    {
        $this->remark = $remark;

        return $this;
    }

    /**
     * Method to set the value of field status
     *
     * @param integer $status
     * @return static
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Method to set the value of field refuse_reason
     *
     * @param string $refuse_reason
     * @return static
     */
    public function setRefuseReason($refuse_reason)
    {
        $this->refuse_reason = $refuse_reason;

        return $this;
    }

    /**
     * Method to set the value of field cancel_time
     *
     * @param string $cancel_time
     * @return static
     */
    public function setCancelTime($cancel_time)
    {
        $this->cancel_time = $cancel_time;

        return $this;
    }

    /**
     * Method to set the value of field cancel_reason
     *
     * @param string $cancel_reason
     * @return static
     */
    public function setCancelReason($cancel_reason)
    {
        $this->cancel_reason = $cancel_reason;

        return $this;
    }

    /**
     * Method to set the value of field created_at
     *
     * @param string $created_at
     * @return static
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Method to set the value of field updated_at
     *
     * @param string $updated_at
     * @return static
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field member_id
     *
     * @return integer
     */
    public function getMemberId()
    {
        return $this->member_id;
    }

    /**
     * Returns the value of field voltage
     *
     * @return integer
     */
    public function getVoltage()
    {
        return $this->voltage;
    }

    /**
     * Returns the value of field brand_id
     *
     * @return integer
     */
    public function getBrandId()
    {
        return $this->brand_id;
    }

    /**
     * Returns the value of field brand_name
     *
     * @return string
     */
    public function getBrandName()
    {
        return $this->brand_name;
    }

    /**
     * Returns the value of field price
     *
     * @return double
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Returns the value of field battery_brand
     *
     * @return string
     */
    public function getBatteryBrand()
    {
        return $this->battery_brand;
    }

    /**
     * Returns the value of field distance
     *
     * @return integer
     */
    public function getDistance()
    {
        return $this->distance;
    }

    /**
     * Returns the value of field guarantee_period
     *
     * @return integer
     */
    public function getGuaranteePeriod()
    {
        return $this->guarantee_period;
    }

    /**
     * Returns the value of field avail_time
     *
     * @return string
     */
    public function getAvailTime()
    {
        return $this->avail_time;
    }

    /**
     * Returns the value of field province
     *
     * @return string
     */
    public function getProvince()
    {
        return $this->province;
    }

    /**
     * Returns the value of field city
     *
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Returns the value of field district
     *
     * @return string
     */
    public function getDistrict()
    {
        return $this->district;
    }

    /**
     * Returns the value of field province_code
     *
     * @return string
     */
    public function getProvinceCode()
    {
        return $this->province_code;
    }

    /**
     * Returns the value of field city_code
     *
     * @return string
     */
    public function getCityCode()
    {
        return $this->city_code;
    }

    /**
     * Returns the value of field district_code
     *
     * @return string
     */
    public function getDistrictCode()
    {
        return $this->district_code;
    }

    /**
     * Returns the value of field detail_addr
     *
     * @return string
     */
    public function getDetailAddr()
    {
        return $this->detail_addr;
    }

    /**
     * Returns the value of field remark
     *
     * @return string
     */
    public function getRemark()
    {
        return $this->remark;
    }

    /**
     * Returns the value of field status
     *
     * @return integer
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Returns the value of field refuse_reason
     *
     * @return string
     */
    public function getRefuseReason()
    {
        return $this->refuse_reason;
    }

    /**
     * Returns the value of field cancel_time
     *
     * @return string
     */
    public function getCancelTime()
    {
        return $this->cancel_time;
    }

    /**
     * Returns the value of field cancel_reason
     *
     * @return string
     */
    public function getCancelReason()
    {
        return $this->cancel_reason;
    }

    /**
     * Returns the value of field created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Returns the value of field updated_at
     *
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'new_bikes';
    }

}
