<?php

namespace Ddb\Models;

/**
 * Orders
 * 
 * @package Ddb\Models
 * @autogenerated by Phalcon Developer Utils
 * @date 2018-05-31, 19:32:02
 * 
 * @method static static findFirstByMemberId($member_id)
 * @method static static[] findByMemberId($member_id)
 * @method static int countByMemberId($member_id)
 * @method static static findFirstByDeviceInfo($device_info)
 * @method static static[] findByDeviceInfo($device_info)
 * @method static int countByDeviceInfo($device_info)
 * @method static static findFirstByNonceStr($nonce_str)
 * @method static static[] findByNonceStr($nonce_str)
 * @method static int countByNonceStr($nonce_str)
 * @method static static findFirstBySign($sign)
 * @method static static[] findBySign($sign)
 * @method static int countBySign($sign)
 * @method static static findFirstBySignType($sign_type)
 * @method static static[] findBySignType($sign_type)
 * @method static int countBySignType($sign_type)
 * @method static static findFirstByBody($body)
 * @method static static[] findByBody($body)
 * @method static int countByBody($body)
 * @method static static findFirstByDetail($detail)
 * @method static static[] findByDetail($detail)
 * @method static int countByDetail($detail)
 * @method static static findFirstByAttach($attach)
 * @method static static[] findByAttach($attach)
 * @method static int countByAttach($attach)
 * @method static static findFirstByOutTradeNo($out_trade_no)
 * @method static static[] findByOutTradeNo($out_trade_no)
 * @method static int countByOutTradeNo($out_trade_no)
 * @method static static findFirstByTotalFee($total_fee)
 * @method static static[] findByTotalFee($total_fee)
 * @method static int countByTotalFee($total_fee)
 * @method static static findFirstBySpbillCreateIp($spbill_create_ip)
 * @method static static[] findBySpbillCreateIp($spbill_create_ip)
 * @method static int countBySpbillCreateIp($spbill_create_ip)
 * @method static static findFirstByTradeType($trade_type)
 * @method static static[] findByTradeType($trade_type)
 * @method static int countByTradeType($trade_type)
 * @method static static findFirstByOpenid($openid)
 * @method static static[] findByOpenid($openid)
 * @method static int countByOpenid($openid)
 * @method static static findFirstByReturnCode($return_code)
 * @method static static[] findByReturnCode($return_code)
 * @method static int countByReturnCode($return_code)
 * @method static static findFirstByReturnMsg($return_msg)
 * @method static static[] findByReturnMsg($return_msg)
 * @method static int countByReturnMsg($return_msg)
 * @method static static findFirstByResultCode($result_code)
 * @method static static[] findByResultCode($result_code)
 * @method static int countByResultCode($result_code)
 * @method static static findFirstByErrCode($err_code)
 * @method static static[] findByErrCode($err_code)
 * @method static int countByErrCode($err_code)
 * @method static static findFirstByErrCodeDes($err_code_des)
 * @method static static[] findByErrCodeDes($err_code_des)
 * @method static int countByErrCodeDes($err_code_des)
 * @method static static findFirstByPrepayId($prepay_id)
 * @method static static[] findByPrepayId($prepay_id)
 * @method static int countByPrepayId($prepay_id)
 * @method static static findFirstByFinishTime($finish_time)
 * @method static static[] findByFinishTime($finish_time)
 * @method static int countByFinishTime($finish_time)
 * @method static static findFirstByCreatedAt($created_at)
 * @method static static[] findByCreatedAt($created_at)
 * @method static int countByCreatedAt($created_at)
 * @method static static findFirstByUpdatedAt($updated_at)
 * @method static static[] findByUpdatedAt($updated_at)
 * @method static int countByUpdatedAt($updated_at)
 */
class Orders extends BaseModel
{

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var integer
     */
    protected $member_id;

    /**
     *
     * @var string
     */
    protected $device_info;

    /**
     *
     * @var string
     */
    protected $nonce_str;

    /**
     *
     * @var string
     */
    protected $sign;

    /**
     *
     * @var string
     */
    protected $sign_type;

    /**
     *
     * @var string
     */
    protected $body;

    /**
     *
     * @var string
     */
    protected $detail;

    /**
     *
     * @var string
     */
    protected $attach;

    /**
     *
     * @var string
     */
    protected $out_trade_no;

    /**
     *
     * @var integer
     */
    protected $total_fee;

    /**
     *
     * @var string
     */
    protected $spbill_create_ip;

    /**
     *
     * @var string
     */
    protected $trade_type;

    /**
     *
     * @var string
     */
    protected $openid;

    /**
     *
     * @var string
     */
    protected $return_code;

    /**
     *
     * @var string
     */
    protected $return_msg;

    /**
     *
     * @var string
     */
    protected $result_code;

    /**
     *
     * @var string
     */
    protected $err_code;

    /**
     *
     * @var string
     */
    protected $err_code_des;

    /**
     *
     * @var string
     */
    protected $prepay_id;

    /**
     *
     * @var string
     */
    protected $finish_time;

    /**
     *
     * @var string
     */
    protected $created_at;

    /**
     *
     * @var string
     */
    protected $updated_at;

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return static
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field member_id
     *
     * @param integer $member_id
     * @return static
     */
    public function setMemberId($member_id)
    {
        $this->member_id = $member_id;

        return $this;
    }

    /**
     * Method to set the value of field device_info
     *
     * @param string $device_info
     * @return static
     */
    public function setDeviceInfo($device_info)
    {
        $this->device_info = $device_info;

        return $this;
    }

    /**
     * Method to set the value of field nonce_str
     *
     * @param string $nonce_str
     * @return static
     */
    public function setNonceStr($nonce_str)
    {
        $this->nonce_str = $nonce_str;

        return $this;
    }

    /**
     * Method to set the value of field sign
     *
     * @param string $sign
     * @return static
     */
    public function setSign($sign)
    {
        $this->sign = $sign;

        return $this;
    }

    /**
     * Method to set the value of field sign_type
     *
     * @param string $sign_type
     * @return static
     */
    public function setSignType($sign_type)
    {
        $this->sign_type = $sign_type;

        return $this;
    }

    /**
     * Method to set the value of field body
     *
     * @param string $body
     * @return static
     */
    public function setBody($body)
    {
        $this->body = $body;

        return $this;
    }

    /**
     * Method to set the value of field detail
     *
     * @param string $detail
     * @return static
     */
    public function setDetail($detail)
    {
        $this->detail = $detail;

        return $this;
    }

    /**
     * Method to set the value of field attach
     *
     * @param string $attach
     * @return static
     */
    public function setAttach($attach)
    {
        $this->attach = $attach;

        return $this;
    }

    /**
     * Method to set the value of field out_trade_no
     *
     * @param string $out_trade_no
     * @return static
     */
    public function setOutTradeNo($out_trade_no)
    {
        $this->out_trade_no = $out_trade_no;

        return $this;
    }

    /**
     * Method to set the value of field total_fee
     *
     * @param integer $total_fee
     * @return static
     */
    public function setTotalFee($total_fee)
    {
        $this->total_fee = $total_fee;

        return $this;
    }

    /**
     * Method to set the value of field spbill_create_ip
     *
     * @param string $spbill_create_ip
     * @return static
     */
    public function setSpbillCreateIp($spbill_create_ip)
    {
        $this->spbill_create_ip = $spbill_create_ip;

        return $this;
    }

    /**
     * Method to set the value of field trade_type
     *
     * @param string $trade_type
     * @return static
     */
    public function setTradeType($trade_type)
    {
        $this->trade_type = $trade_type;

        return $this;
    }

    /**
     * Method to set the value of field openid
     *
     * @param string $openid
     * @return static
     */
    public function setOpenid($openid)
    {
        $this->openid = $openid;

        return $this;
    }

    /**
     * Method to set the value of field return_code
     *
     * @param string $return_code
     * @return static
     */
    public function setReturnCode($return_code)
    {
        $this->return_code = $return_code;

        return $this;
    }

    /**
     * Method to set the value of field return_msg
     *
     * @param string $return_msg
     * @return static
     */
    public function setReturnMsg($return_msg)
    {
        $this->return_msg = $return_msg;

        return $this;
    }

    /**
     * Method to set the value of field result_code
     *
     * @param string $result_code
     * @return static
     */
    public function setResultCode($result_code)
    {
        $this->result_code = $result_code;

        return $this;
    }

    /**
     * Method to set the value of field err_code
     *
     * @param string $err_code
     * @return static
     */
    public function setErrCode($err_code)
    {
        $this->err_code = $err_code;

        return $this;
    }

    /**
     * Method to set the value of field err_code_des
     *
     * @param string $err_code_des
     * @return static
     */
    public function setErrCodeDes($err_code_des)
    {
        $this->err_code_des = $err_code_des;

        return $this;
    }

    /**
     * Method to set the value of field prepay_id
     *
     * @param string $prepay_id
     * @return static
     */
    public function setPrepayId($prepay_id)
    {
        $this->prepay_id = $prepay_id;

        return $this;
    }

    /**
     * Method to set the value of field finish_time
     *
     * @param string $finish_time
     * @return static
     */
    public function setFinishTime($finish_time)
    {
        $this->finish_time = $finish_time;

        return $this;
    }

    /**
     * Method to set the value of field created_at
     *
     * @param string $created_at
     * @return static
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Method to set the value of field updated_at
     *
     * @param string $updated_at
     * @return static
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field member_id
     *
     * @return integer
     */
    public function getMemberId()
    {
        return $this->member_id;
    }

    /**
     * Returns the value of field device_info
     *
     * @return string
     */
    public function getDeviceInfo()
    {
        return $this->device_info;
    }

    /**
     * Returns the value of field nonce_str
     *
     * @return string
     */
    public function getNonceStr()
    {
        return $this->nonce_str;
    }

    /**
     * Returns the value of field sign
     *
     * @return string
     */
    public function getSign()
    {
        return $this->sign;
    }

    /**
     * Returns the value of field sign_type
     *
     * @return string
     */
    public function getSignType()
    {
        return $this->sign_type;
    }

    /**
     * Returns the value of field body
     *
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Returns the value of field detail
     *
     * @return string
     */
    public function getDetail()
    {
        return $this->detail;
    }

    /**
     * Returns the value of field attach
     *
     * @return string
     */
    public function getAttach()
    {
        return $this->attach;
    }

    /**
     * Returns the value of field out_trade_no
     *
     * @return string
     */
    public function getOutTradeNo()
    {
        return $this->out_trade_no;
    }

    /**
     * Returns the value of field total_fee
     *
     * @return integer
     */
    public function getTotalFee()
    {
        return $this->total_fee;
    }

    /**
     * Returns the value of field spbill_create_ip
     *
     * @return string
     */
    public function getSpbillCreateIp()
    {
        return $this->spbill_create_ip;
    }

    /**
     * Returns the value of field trade_type
     *
     * @return string
     */
    public function getTradeType()
    {
        return $this->trade_type;
    }

    /**
     * Returns the value of field openid
     *
     * @return string
     */
    public function getOpenid()
    {
        return $this->openid;
    }

    /**
     * Returns the value of field return_code
     *
     * @return string
     */
    public function getReturnCode()
    {
        return $this->return_code;
    }

    /**
     * Returns the value of field return_msg
     *
     * @return string
     */
    public function getReturnMsg()
    {
        return $this->return_msg;
    }

    /**
     * Returns the value of field result_code
     *
     * @return string
     */
    public function getResultCode()
    {
        return $this->result_code;
    }

    /**
     * Returns the value of field err_code
     *
     * @return string
     */
    public function getErrCode()
    {
        return $this->err_code;
    }

    /**
     * Returns the value of field err_code_des
     *
     * @return string
     */
    public function getErrCodeDes()
    {
        return $this->err_code_des;
    }

    /**
     * Returns the value of field prepay_id
     *
     * @return string
     */
    public function getPrepayId()
    {
        return $this->prepay_id;
    }

    /**
     * Returns the value of field finish_time
     *
     * @return string
     */
    public function getFinishTime()
    {
        return $this->finish_time;
    }

    /**
     * Returns the value of field created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Returns the value of field updated_at
     *
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'orders';
    }

}
