<?php

namespace Ddb\Models;

/**
 * Phinxlog
 * 
 * @package Ddb\Models
 * @autogenerated by Phalcon Developer Utils
 * @date 2018-04-25, 13:10:52
 * 
 * @method static static findFirstByVersion($version)
 * @method static static[] findByVersion($version)
 * @method static int countByVersion($version)
 * @method static static findFirstByMigrationName($migration_name)
 * @method static static[] findByMigrationName($migration_name)
 * @method static int countByMigrationName($migration_name)
 * @method static static findFirstByStartTime($start_time)
 * @method static static[] findByStartTime($start_time)
 * @method static int countByStartTime($start_time)
 * @method static static findFirstByEndTime($end_time)
 * @method static static[] findByEndTime($end_time)
 * @method static int countByEndTime($end_time)
 * @method static static findFirstByBreakpoint($breakpoint)
 * @method static static[] findByBreakpoint($breakpoint)
 * @method static int countByBreakpoint($breakpoint)
 */
class Phinxlog extends BaseModel
{

    /**
     *
     * @var string
     */
    protected $version;

    /**
     *
     * @var string
     */
    protected $migration_name;

    /**
     *
     * @var string
     */
    protected $start_time;

    /**
     *
     * @var string
     */
    protected $end_time;

    /**
     *
     * @var integer
     */
    protected $breakpoint;

    /**
     * Method to set the value of field version
     *
     * @param string $version
     * @return static
     */
    public function setVersion($version)
    {
        $this->version = $version;

        return $this;
    }

    /**
     * Method to set the value of field migration_name
     *
     * @param string $migration_name
     * @return static
     */
    public function setMigrationName($migration_name)
    {
        $this->migration_name = $migration_name;

        return $this;
    }

    /**
     * Method to set the value of field start_time
     *
     * @param string $start_time
     * @return static
     */
    public function setStartTime($start_time)
    {
        $this->start_time = $start_time;

        return $this;
    }

    /**
     * Method to set the value of field end_time
     *
     * @param string $end_time
     * @return static
     */
    public function setEndTime($end_time)
    {
        $this->end_time = $end_time;

        return $this;
    }

    /**
     * Method to set the value of field breakpoint
     *
     * @param integer $breakpoint
     * @return static
     */
    public function setBreakpoint($breakpoint)
    {
        $this->breakpoint = $breakpoint;

        return $this;
    }

    /**
     * Returns the value of field version
     *
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Returns the value of field migration_name
     *
     * @return string
     */
    public function getMigrationName()
    {
        return $this->migration_name;
    }

    /**
     * Returns the value of field start_time
     *
     * @return string
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    /**
     * Returns the value of field end_time
     *
     * @return string
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    /**
     * Returns the value of field breakpoint
     *
     * @return integer
     */
    public function getBreakpoint()
    {
        return $this->breakpoint;
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'phinxlog';
    }

}
