<?php

namespace Ddb\Models;

/**
 * Recommends
 * 
 * @package Ddb\Models
 * @autogenerated by Phalcon Developer Utils
 * @date 2018-06-11, 15:37:39
 * 
 * @method static static findFirstByTId($t_id)
 * @method static static[] findByTId($t_id)
 * @method static int countByTId($t_id)
 * @method static static findFirstByBId($b_id)
 * @method static static[] findByBId($b_id)
 * @method static int countByBId($b_id)
 * @method static static findFirstByCreatedAt($created_at)
 * @method static static[] findByCreatedAt($created_at)
 * @method static int countByCreatedAt($created_at)
 * @method static static findFirstByUpdatedAt($updated_at)
 * @method static static[] findByUpdatedAt($updated_at)
 * @method static int countByUpdatedAt($updated_at)
 */
class Recommends extends BaseModel
{

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var integer
     */
    protected $t_id;

    /**
     *
     * @var integer
     */
    protected $b_id;

    /**
     *
     * @var string
     */
    protected $created_at;

    /**
     *
     * @var string
     */
    protected $updated_at;

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return static
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field t_id
     *
     * @param integer $t_id
     * @return static
     */
    public function setTId($t_id)
    {
        $this->t_id = $t_id;

        return $this;
    }

    /**
     * Method to set the value of field b_id
     *
     * @param integer $b_id
     * @return static
     */
    public function setBId($b_id)
    {
        $this->b_id = $b_id;

        return $this;
    }

    /**
     * Method to set the value of field created_at
     *
     * @param string $created_at
     * @return static
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Method to set the value of field updated_at
     *
     * @param string $updated_at
     * @return static
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field t_id
     *
     * @return integer
     */
    public function getTId()
    {
        return $this->t_id;
    }

    /**
     * Returns the value of field b_id
     *
     * @return integer
     */
    public function getBId()
    {
        return $this->b_id;
    }

    /**
     * Returns the value of field created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Returns the value of field updated_at
     *
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'recommends';
    }

}
